# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/29ecb4fc-9139-4751-9e43-f7930e1b6116";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/184ea4ab-de77-4ed4-908a-3e65dc58a1c7"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
