keys:
  - &madeline ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILR5/w+gVjwspJzU5qMRDqU4fGyH8iatsfYLgfoBm3Ix
  - &chocola age1zqhtn7pqm2cddgfgdn5dumup97hskyg4yere8fgqle39n998sfnq4cwpk0

creation_rules:
  - path_regex: secrets/chocola\.yaml$
    key_groups:
      - age:
        - *madeline
        - *chocola
